### ISSUE TITLE
Better error-handling for library usage.

### ISSUE THREAD

**Issue by vjpr** [7sempra/rosetta#1]
Firstly, love the idea of Rosetta. Very clever! I need a solution like this because I have Twitter Bootstrap variables in less and my own variables in stylus. I want to put all my vars in a `.rose` file and compile a less and stylus version, and having them accessible in js will be cool too! I'm using it in a library which runs when `watchr` sees changes to rose files.

On to the issue...

Parse errors appear to be handled like so:

```
function _handleError(e) {
  if (e instanceof errors.CompileError) {
    _printError(e);
    process.exit(1);
  } else {
    throw e;
  }
}
```

They can occur on a `#compile` which has a callback. The error should be passed back to this callback Node.js style.

Use of `process.exit()` prevents it from being used as a library.

**Comment by 7sempra** [comment]
Fixed in 89f2119ca222adb636ac45fb9ea0970715344088. Sorry for the wait!
