### ISSUE TITLE
Colors aren't handled correctly

### ISSUE THREAD

**Issue by Cybolic** [7sempra/rosetta#2]
Hex colors that start with #00 are truncated, so f.x. `#0096FF` becomes `#96ff`.

RGB(A) colors also seem not to work and are picky about white space:

E.g.

```
$color = rgba(255, 100, 0, 1.0) -> @color: rgba(255,255,255,1);
$color = rgb(255, 100, 0)       -> @color: #ffffff;
$color = rgba(255,100,0,1)      -> fails: LexError: Unexpected symbol: 1
$color = rgb(255,100,0)         -> fails: LexError: Unexpected symbol: 1
```

**Comment by Cybolic** [comment]
The bug causing rgb(A) vales to only use red is fixed in my branch with this commit: https://github.com/Cybolic/rosetta/commit/d023edff69c62a1da30b1e65f68c78779465fecd

**Comment by Cybolic** [comment]
The bug causing hex values to be missing their leading zeros is fixed in my branch with this commit: https://github.com/Cybolic/rosetta/commit/44a5b718ed260801fa3221b03afb1e8b2b1d4cc4

**Comment by Cybolic** [comment]
The LexError still isn't fixed, but I can live with that.

**Comment by 7sempra** [comment]
Thanks for the PR! I just fixed the lexing error as well in 7sempra@4080b6ab75fa526f1f41b4c63fd067182e4916bf.

**Comment by Cybolic** [comment]
Excellent. Could you push an update to npm? Then I can retire my fork.

**Comment by 7sempra** [comment]
Yep. Finishing up one other change and then I'll push.

**Comment by 7sempra** [comment]
Done (v0.2.0).
