### ISSUE TITLE
Synchronous api as an option

### ISSUE THREAD

**Issue by vjpr** [7sempra/rosetta#4]
I am trying to integrate into the [Mincer](https://github.com/nodeca/mincer) project. This now requires synchronous compilation.

I might take a look into it when I can.

---

Looks like there are only two methods that are async during `compile`:

```
function _readTemplate(templatePath, root, options, callback) {
  fs.readFile(templatePath, 'utf8', function(err, templateData) {
    if (err) {
      throw err;
    }

    _readPreamble(root, options, templateData, callback);
  });
}

function _readPreamble(root, options, template, callback) {
  fs.readFile(__dirname + '/jstemplates/preamble.js', 'utf8',
  function(err, preambleData) {
    if (err) {
      throw err; // TODO
    }

    callback(null, _compile(root, options, preambleData, template));
  });
}
```

**Comment by vjpr** [comment]
Yep changing those two calls and we have synchronous support.

How do you want to support sync? Options:-
1. Change these two methods to sync calls.
2. Compile option and keep callbacks (CON: not Node.js std lib style).
3. Use different method names - `writeFilesSync` and `compileSync`.

**Comment by 7sempra** [comment]
I favor simply moving to option 1 (see pull request). It doesn't really make sense to have async options for a compiler anyway.
